# Generated by Django 6.0.2 on 2026-02-06 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_format', models.CharField(choices=[('PYTHON', 'Python Script'), ('R', 'R Script'), ('CSV', 'Data/CSV'), ('CPP', 'C++ Binary'), ('XLSX', 'Excel/VBA'), ('SAS', 'SAS Base')], max_length=20)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('code_path', models.CharField(help_text='Link to Git or Network Path', max_length=500)),
                ('data_path', models.CharField(help_text='Path to training CSV/Database', max_length=500)),
                ('risk_rating', models.CharField(choices=[('HIGH', 'High Risk (Tier 1)'), ('MEDIUM', 'Medium Risk (Tier 2)'), ('LOW', 'Low Risk (Tier 3)')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='developed_models', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_assets', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='ModelChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes_json', models.JSONField(help_text='Structured description of proposed changes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_changes', to=settings.AUTH_USER_MODEL)),
                ('target_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='model_inventory.modelasset')),
            ],
        ),
    ]
